### ISSUE TITLE
DOMException with google chrome 

### ISSUE THREAD

**Issue by Jovennan** [emtudo/school-spa#1]
Conforme imagem abaixo, estou tendo dificuldades de acessar o projeto no modo dev pelo google chrome, no firefox executa normalmente.

![screenshot from 2018-06-21 10 43 05](https://user-images.githubusercontent.com/1591954/41722881-135f4c42-7540-11e8-83b7-be2630d90b8a.png)

**Comment by emtudo** [comment]
Estranho você ver este erro, o que você tentou fazer?

Não consegui reproduzir, estranho que mostra a URL de login, mas você já está logado, senão nem veria o que está vendo dos menus.

**Comment by emtudo** [comment]
@Jovennan descobri o problema, outra pessoa me disse os erros que aparece no log.

Eis aqui a solução: https://www.youtube.com/watch?v=tZxgxteGl0Q

**Comment by Jovennan** [comment]
Desculpa não ter visto antes
