### ISSUE TITLE
Logout & login mostrar registro

### ISSUE THREAD

**Issue by flavianohonorato** [emtudo/school-spa#2]
Fiz um teste aqui, não sei se foi só aqui comigo, adicionei uma nova escola, mas não aparecia no select pra alterar entre escolas, nem atualizando o navegador, tive que deslogar e logar novamente, só aí exibiu a nova escola cadastrada.
<img width="256" alt="screen shot 2018-06-23 at 11 20 10" src="https://user-images.githubusercontent.com/4780299/41810582-6c1edaee-76d7-11e8-8d13-f38fc8999040.png">

**Comment by emtudo** [comment]
Estou ciente desse bug, precisa haver uma atualização apenas, usar um event bus ou o vuex.

Mas fique a vontade para enviar uma PR e contribuir com o projeto.
